Repository Woynert/buenavida-back, pull requests merged in 2022-11, with the labels that each got.

#12 Singup
  src/controller/session.go
  src/server.go
Labels: Sesión

#13 /Store endpoint: Filter search
  src/controller/store.go
  src/database/fuzzy.go
  src/database/interfaces.go
  src/database/mongo.go
  src/go.mod
  src/go.sum
  src/middleware.go
  src/server.go
  util/import-mongo.sh
Labels: Tienda

#14 Session refresh
  src/controller/session.go
  src/middleware.go
  src/sql/procedures.sql
  src/sql/sample-data.sql
  src/token/token.go
Labels: Sesión

#17 /payment endpoint
  src/.env
  src/controller/cart.go
  src/controller/session.go
  src/controller/store.go
  src/database/database.go
  src/database/fuzzy.go
  src/database/mongo.go
  src/database/postgres.go
  src/go.mod
  src/go.sum
  src/middleware.go
  src/server.go
  src/sql/procedures.sql
  src/sql/sample-data.sql
  src/sql/tables.sql
Labels: Pago

#18 Endpoint add item to favorite
  src/controller/cart.go
  src/controller/favorite.go
  src/server.go
Labels: Favoritos

#19 Endopoint Remove favorites
  src/controller/favorite.go
Labels: Favoritos

#22 Get user information, including favorite items
  src/controller/user.go
  src/server.go
Labels: Favoritos

#23 Include item count in search endpoint
  data/json/productsdup.json
  src/controller/store.go
  util/import-mongo.sh
Labels: Tienda
